Replay parsing
SprocketBot/replay-parse-service pull request #6
Opened 2022-02-14 22:10 UTC by zachstence

2022-02-19 03:11 UTC, bwpikaard approved these changes

2022-02-20 03:51 UTC, 0c370t requested changes
Couple questions, also need to make sure we properly report errors

2022-02-20 03:51 UTC, 0c370t commented on src/files.py
> +    path = f"{TEMP_DIR}/{object_name}"
Does the temporary directory get created if it does not already exist?

2022-02-20 03:51 UTC, 0c370t commented on src/files.py
> +TEMP_DIR = os.path.join(os.getcwd(), config["tempDir"])
Not sure if this is what we will want when in a container, as this will prevent absolute urls from being used, I think (i.e. /tmp)

2022-02-20 03:51 UTC, 0c370t commented on src/main.py
> +    files.clear_tempdir()
Should this be more specific?

2022-02-20 03:51 UTC, 0c370t commented on src/main.py
> +        result=result
Are we returning the data twice?

2022-02-20 18:27 UTC, zachstence commented on src/main.py
> +        result=result
The data is returned on the progress queue if updates are being published. If not, we return the data through the celery backend.

2022-02-21 02:09 UTC, zachstence commented on src/files.py
> +    path = f"{TEMP_DIR}/{object_name}"
[cbf7f3b](https://github.com/SprocketBot/replay-parse-service/pull/6/commits/cbf7f3b6d38fccc23109e3c14fbaba11580dcdb5)

2022-02-21 02:09 UTC, zachstence commented on src/files.py
> +TEMP_DIR = os.path.join(os.getcwd(), config["tempDir"])
[cbf7f3b](https://github.com/SprocketBot/replay-parse-service/pull/6/commits/cbf7f3b6d38fccc23109e3c14fbaba11580dcdb5)

2022-02-21 02:10 UTC, zachstence commented on src/main.py
> +    files.clear_tempdir()
Nah

2022-02-21 02:10 UTC, zachstence commented on src/files.py
> +    path = f"{TEMP_DIR}/{object_name}"
Ye

2022-02-21 22:09 UTC, merged